[package]
name = "snake"
version = "0.1.0"
authors = ["sarowish"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
tui = "0.12"
termion = "1.5"

[features]
